temp test

diff --git a/.github/workflows/aio.yml b/.github/workflows/aio.yml
--- a/.github/workflows/aio.yml
+++ b/.github/workflows/aio.yml
@@ -7,17 +7,32 @@ on:
         description: 'Branch or tag of the wazuh-automation repository'
         required: true
         default: 'main'
-      SYSTEMS:
-        description: 'Operating Systems (list of comma-separated quoted strings enclosed in square brackets)'
+      OS_LIST:
+        description: 'Operating Systems (comma-separated string list)'
         required: true
         default: '["CentOS_8", "AmazonLinux_2", "Ubuntu_22", "RHEL8"]'
         type: string
+      COMMIT_LIST:
+        description: 'Wazuh components revisions (comma-separated string list) ["indexer", "server", "dashboard", "agent"]'
+        required: true
+        default: '["latest", "latest", "latest", "latest"]'
+        type: string
+      ENVIRONMENT:
+        description: 'Environment to run the playbook'
+        required: true
+        default: 'development'
+        type: choice
+        options:
+          - development
+          - prerelease
+          - production
       VERBOSITY:
         description: 'Verbosity level on playbooks execution'
         required: true
-        default: '-v'
+        default: 'normal'
         type: choice
         options:
+          - normal
           - -v
           - -vv
           - -vvv
@@ -27,6 +42,9 @@ on:
 env:
   COMPOSITE_NAME: "linux-SUBNAME-amd64"
   ALLOCATOR_PATH: "/tmp/allocator_instance"
+  DEPLOY_TEMP_DIR: "/tmp/wazuh-ansible"
+  ARTIFACTS_URLS_FILE_TEMP: "artifacts_urls.yml"
+  PRESIGNED_OUTPUT_FILE: "artifacts_urls_presigned.yml"
 permissions:
   id-token: write # JWT
   contents: read # actions/checkout
@@ -40,14 +58,13 @@ jobs:
       - name: Compute outputs
         id: compute-outputs
         run: |
-          # Set SYSTEMS_LIST
-          if [ "${{ inputs.SYSTEMS }}" != "null" && "${{ inputs.SYSTEMS }}" != "" ]; then
-            SYSTEMS_LIST=${{ inputs.SYSTEMS }}
+          # Set OS_LIST
+          if [[ "${{ inputs.OS_LIST }}" != "null" && "${{ inputs.OS_LIST }}" != "" ]]; then
+            OS_LIST='${{ inputs.OS_LIST }}'
           else
-            SYSTEMS_LIST='["CentOS_8", "AmazonLinux_2", "Ubuntu_22", "RHEL8"]'
+            OS_LIST='["CentOS_8", "AmazonLinux_2", "Ubuntu_22", "RHEL8"]'
           fi
-          echo "SYSTEMS_JSON=$(echo $SYSTEMS_LIST | jq -c '.')" >> $GITHUB_OUTPUT
-          echo "Systems JSON: $SYSTEMS_JSON"
+          echo "OS_LIST=$OS_LIST" >> $GITHUB_OUTPUT
 
           # Set WAZUH_TEMPLATE_BRANCH
           if [ "${{ github.event_name }}" == "pull_request" ]; then
@@ -61,25 +78,180 @@ jobs:
           echo "WAZUH_TEMPLATE_BRANCH=$WAZUH_TEMPLATE_BRANCH" >> $GITHUB_OUTPUT
 
           # Set VERBOSITY
-          if [ "${{ inputs.VERBOSITY }}" != "null" && "${{ inputs.VERBOSITY }}" != "" ]; then
-            VERBOSITY=${{ inputs.VERBOSITY }}
+          if [[ "${{ inputs.VERBOSITY }}" != "null" && "${{ inputs.VERBOSITY }}" != "normal" ]]; then
+            VERBOSITY="${{ inputs.VERBOSITY }}"
           else
-            VERBOSITY='-v'
+            VERBOSITY=''
           fi
           echo "VERBOSITY=$VERBOSITY" >> $GITHUB_OUTPUT
           echo "Verbosity level: $VERBOSITY"
+
+          # Set ENVIRONMENT
+          if [[ "${{ inputs.ENVIRONMENT }}" != "null" && "${{ inputs.ENVIRONMENT }}" != "" ]]; then
+            ENVIRONMENT="${{ inputs.ENVIRONMENT }}"
+          else
+            ENVIRONMENT='development'
+          fi
+          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
+          echo "Environment: $ENVIRONMENT"
+
+          # Set REVISIONS
+          if [[ "${{ inputs.COMMIT_LIST }}" != "null" && "${{ inputs.COMMIT_LIST }}" != "" ]]; then
+            COMMIT_LIST='${{ inputs.COMMIT_LIST }}'
+          else
+            COMMIT_LIST='["latest", "latest", "latest", "latest"]'
+          fi
+          echo "COMMIT_LIST=$COMMIT_LIST" >> $GITHUB_OUTPUT
+          echo "Revision list (indexer, server, dashboard, agent): $COMMIT_LIST"
     outputs:
-      SYSTEMS_JSON: ${{ steps.compute-outputs.outputs.SYSTEMS_JSON }}
-      VERBOSITY: ${{ steps.compute-outputs.outputs.VERBOSITY }}
+      OS_LIST: ${{ steps.compute-outputs.outputs.OS_LIST }}
       WAZUH_TEMPLATE_BRANCH: ${{ steps.compute-outputs.outputs.WAZUH_TEMPLATE_BRANCH }}
+      VERBOSITY: ${{ steps.compute-outputs.outputs.VERBOSITY }}
+      ENVIRONMENT: ${{ steps.compute-outputs.outputs.ENVIRONMENT }}
+      COMMIT_LIST: ${{ steps.compute-outputs.outputs.COMMIT_LIST }}
+  package-urls:
+    name: Generate package URLs (if applicable)
+    runs-on: ubuntu-latest
+    needs: setup-runner
+    if: ${{ needs.setup-runner.outputs.ENVIRONMENT == 'development' }}
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
+          aws-region: us-east-1
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          path: wazuh-ansible/
+      - name: Download S3 package URIs file (if applicable)
+        run: |
+          # Generate a pre-signed URL for the S3 file
+          S3_BUCKET="xdrsiem-devops-wazuh-artifacts"
+          S3_KEY="deployment/5.0/artifacts_urls.yml"
+          EXPIRATION=3600 # 1 hour
+          PRESIGNED_URL=$(aws s3 presign s3://$S3_BUCKET/$S3_KEY --expires-in $EXPIRATION --region us-west-1)
+          echo "Generated pre-signed URL: $PRESIGNED_URL"
+
+          # Create a temporary directory to store files
+          mkdir -p "${{ env.DEPLOY_TEMP_DIR }}"
+
+          # Download the file using the pre-signed URL
+          curl -o $DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP "$PRESIGNED_URL"
+
+          # Verify the file was downloaded
+          if [ -f $DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP ]; then
+            echo "S3 package URIs file downloaded successfully."
+          else
+            echo "Failed to download S3 package URIs file." >&2
+            exit 1
+          fi
+      - name: Generate the variables file (signing each package URI)
+        run: |
+          # Define necessary variables
+          VERSION_FILE="wazuh-ansible/VERSION.json"
+          WAZUH_VERSION=$(jq -r '.version' "$VERSION_FILE")
+          WAZUH_MAJOR=$(echo "$WAZUH_VERSION" | cut -d '.' -f 1)
+          COMMIT_LIST='${{ needs.setup-runner.outputs.COMMIT_LIST }}'
+          OUTPUT_FILE="/tmp/artifacts_urls_processed.yml"
+
+          # Extract revisions using jq
+          INDEXER_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[0]')
+          SERVER_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[1]')
+          DASHBOARD_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[2]')
+          AGENT_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[3]')
+
+          # Verify if the input file exists
+          if [ ! -f "$DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP" ]; then
+            echo "The input file $DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP does not exist." >&2
+            exit 1
+          fi
+
+          # Process the file line by line (replacing ocurrences)
+          while IFS= read -r line || [ -n "$line" ]; do
+            # Skip empty lines and comments
+            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
+              echo "$line" >> "$OUTPUT_FILE"
+              continue
+            fi
+
+            # Replace MAJOR with the major version
+            line=${line//MAJOR/$WAZUH_MAJOR}
+
+            # Replace WAZUH_VERSION with the full version
+            line=${line//WAZUH_VERSION/$WAZUH_VERSION}
+
+            # Handle the different component revisions based on the URL pattern
+            if [[ "$line" == *"wazuh_indexer_url"* ]]; then
+              line=${line//latest/$INDEXER_COMMIT}
+            elif [[ "$line" == *"wazuh_server_url"* ]]; then
+              line=${line//latest/$SERVER_COMMIT}
+            elif [[ "$line" == *"wazuh_dashboard_url"* ]]; then
+              line=${line//latest/$DASHBOARD_COMMIT}
+            elif [[ "$line" == *"wazuh_agent_url"* ]]; then
+              line=${line//latest/$AGENT_COMMIT}
+            fi
+
+            # Append the processed line to the output file
+            echo "$line" >> "$OUTPUT_FILE"
+          done < "$DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP"
+
+          # Verify the output file
+          if [ -f "$OUTPUT_FILE" ]; then
+            echo "The downloaded file artifacts_urls.yml was successfully processed at $OUTPUT_FILE."
+          else
+            echo "Failed to create processed artifacts_urls.yml file." >&2
+            exit 1
+          fi
+
+          # Generate the presigned URLs for each package
+          while IFS= read -r line || [ -n "$line" ]; do
+            # Skip empty lines and comments
+            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
+              echo "$line" >> "$DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE"
+              continue
+            fi
+
+            # Extract both package_name and package_s3_uri from the line
+            if [[ "$line" =~ ^([a-zA-Z0-9_]+):[[:space:]]*s3://([^[:space:]]+) ]]; then
+              PACKAGE_NAME="${BASH_REMATCH[1]}"
+              PACKAGE_S3_URI="s3://${BASH_REMATCH[2]}"
+
+              # Generate a pre-signed URL for the S3 URI
+              echo "Generating pre-signed URL for $PACKAGE_NAME..."
+              PRESIGNED_URL=$(aws s3 presign "$PACKAGE_S3_URI" --expires-in 43200 --region us-west-1)
+              presigned_url_line="$PACKAGE_NAME: \"$PRESIGNED_URL\""
+
+              # Append the processed line to the output file
+              echo "$presigned_url_line" >> "$DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE"
+            else
+              echo "Skipping line for presigning (no S3 URI found):"
+              echo "$line"
+            fi
+          done < "$OUTPUT_FILE"
+
+          # Verify the presigned urls file
+          if [ -f "$DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE" ]; then
+            echo "Presigned URLs file created successfully at $DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE."
+          else
+            echo "Failed to create presigned artifacts_urls.yml file." >&2
+            exit 1
+          fi
+      - name: Save presigned URLs file to artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: presigned-artifacts-urls-${{ github.run_id }}
+          path: "${{ env.DEPLOY_TEMP_DIR }}/${{ env.PRESIGNED_OUTPUT_FILE }}"
   start-runner:
     name: Start EC2 instance using allocator and run ansible playbook
     runs-on: ubuntu-latest
-    needs: setup-runner
+    needs:
+      - setup-runner
+      - package-urls
     strategy:
       fail-fast: false # all jobs will run even if one fails
       matrix:
-        system: ${{ fromJson(needs.setup-runner.outputs.SYSTEMS_JSON) }}
+        system: ${{ fromJson(needs.setup-runner.outputs.OS_LIST) }}
     steps:
       - name: Configure AWS credentials (assume role)
         uses: aws-actions/configure-aws-credentials@v4
@@ -107,6 +279,8 @@ jobs:
           pip install ansible-core==2.16
           ansible-galaxy collection install community.general
           ansible-galaxy collection install community.docker
+          mkdir -p ${{ env.ALLOCATOR_PATH }}
+          mkdir -p ${{ env.DEPLOY_TEMP_DIR }}
       - name: Set COMPOSITE_NAME variable
         run: |
           case "${{ matrix.system }}" in
@@ -151,6 +325,12 @@ jobs:
             --track-output $ALLOCATOR_PATH/track.yml --inventory-output $ALLOCATOR_PATH/inventory.yml --instance-name gha_ansible_${{ matrix.system }}_${{ github.run_id }} \
             --label-team devops --label-termination-date 1d
 
+          instance_id=$(grep '^identifier' $ALLOCATOR_PATH/track.yml | awk '{print $2}')
+          private_ip=$(aws ec2 describe-instances \
+            --instance-ids $instance_id \
+            --query 'Reservations[*].Instances[*].PrivateIpAddress' \
+            --output text)
+
           # Parse the new inventory format
           ansible_host=$(yq e '.all.hosts[].ansible_host' $ALLOCATOR_PATH/inventory.yml)
           ansible_port=$(yq e '.all.hosts[].ansible_port' $ALLOCATOR_PATH/inventory.yml)
@@ -158,11 +338,12 @@ jobs:
           ansible_ssh_private_key_file=$(yq e '.all.hosts[].ansible_ssh_private_key_file' $ALLOCATOR_PATH/inventory.yml)
           ansible_ssh_common_args=$(yq e '.all.hosts[].ansible_ssh_common_args' $ALLOCATOR_PATH/inventory.yml)
 
-          echo "[aio]" > $ALLOCATOR_PATH/inventory
-          echo "$ansible_host ansible_port=$ansible_port ansible_user=$ansible_user ansible_ssh_private_key_file=$ansible_ssh_private_key_file ansible_ssh_common_args='$ansible_ssh_common_args'" >> $ALLOCATOR_PATH/inventory
-          echo "[aio:vars]" >> $ALLOCATOR_PATH/inventory
-          echo "wazuh_template_branch=${{ needs.setup-runner.outputs.WAZUH_TEMPLATE_BRANCH }}" >> $ALLOCATOR_PATH/inventory
-
+          echo "[all]" > $ALLOCATOR_PATH/inventory
+          echo "aio ansible_host=$ansible_host private_ip=$private_ip ansible_user=$ansible_user" >> $ALLOCATOR_PATH/inventory
+          echo "[all:vars]" >> $ALLOCATOR_PATH/inventory
+          echo "ansible_port=$ansible_port" >> $ALLOCATOR_PATH/inventory
+          echo "ansible_ssh_common_args='$ansible_ssh_common_args'" >> $ALLOCATOR_PATH/inventory
+          echo "ansible_ssh_private_key_file=$ansible_ssh_private_key_file" >> $ALLOCATOR_PATH/inventory
       - name: Save ALLOCATOR_PATH directory as artifact
         uses: actions/upload-artifact@v4
         with:
@@ -170,9 +351,20 @@ jobs:
           path: ${{ env.ALLOCATOR_PATH }}
       - name: Check out the codebase.
         uses: actions/checkout@v4
+        with:
+          path: wazuh-ansible/
+      - name: Download the presigned urls file artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: presigned-artifacts-urls-${{ github.run_id }}
+          path: ${{ env.DEPLOY_TEMP_DIR }}
+      - name: Copy the presigned urls file to Ansible roles variables path
+        run: |
+          # Copy the presigned URLs file to the Ansible roles variables path
+          cp $DEPLOY_TEMP_DIR/${{ env.PRESIGNED_OUTPUT_FILE }} wazuh-ansible/roles/vars/artifacts_urls.yml
       - name: Ansible Playbook run Wazuh AIO Single instance
         run: |
-          ansible-playbook ./.github/playbooks/aio-wazuh.yml \
+          ansible-playbook wazuh-ansible/.github/playbooks/aio-wazuh.yml \
           -i $ALLOCATOR_PATH/inventory \
           -l all \
           ${{ needs.setup-runner.outputs.VERBOSITY }}
@@ -185,7 +377,7 @@ jobs:
     strategy:
       fail-fast: false # all jobs will run even if one fails
       matrix:
-        system: ${{ fromJson(needs.setup-runner.outputs.SYSTEMS_JSON) }}
+        system: ${{ fromJson(needs.setup-runner.outputs.OS_LIST) }}
     if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
     steps:
       - name: Configure AWS credentials
